services:
  my-client:
    build:
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      VITE_VAR: ${VITE_VAR}
      VAR: ${VITE_VAR}
      BASE_URL: ${BASE_URL}
      VITE_AUTH0_DOMAIN: ${VITE_AUTH0_DOMAIN}
      VITE_AUTH0_CLIENT_ID: ${VITE_AUTH0_CLIENT_ID}
      AUTH0_EMAIL: ${AUTH0_EMAIL}
      AUTH0_PASSWORD: ${AUTH0_PASSWORD}
    volumes:
      - /app/node_modules
      - ./src:/app/src
      - ./public:/app/public
      - ./cypress/screenshots:/app/cypress/screenshots
