services:
  my-client:
    build:
      dockerfile: Dockerfile.test
      args:
        VITE_VAR: ${VITE_VAR}
        VAR: ${VITE_VAR}
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
