FROM cypress/browsers:node-20.16.0-chrome-127.0.6533.88-1-ff-128.0.3-edge-127.0.2651.74-1

ARG VAR
ARG VITE_VAR
ARG BASE_URL

ENV VAR=$VAR
ENV VITE_VAR=$VITE_VAR
ENV BASE_URL=$BASE_URL

WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
EXPOSE 3000
RUN npm run build
CMD ["npm", "run", "preview", "--", "--host"]